-- Temporarily disable RLS for testing
ALTER TABLE public.user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.slides DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.slide_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_shares DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_ratings DISABLE ROW LEVEL SECURITY;
